### ISSUE TITLE
Cannot install/run

### ISSUE THREAD

**Issue by coffseducation** [k3karthic/bitwarden-to-keepass#10]
In the directory I have downloaded convert.py to:

convert.py [-h] /home/anarcho/Downloads/bitwarden_export_20230912103911.json -o pass.bdbx
convert.py: command not found

If I try python, pip3 or pipx I get:

 Neither 'setup.py' nor 'pyproject.toml' found

**Comment by coffseducation** [comment]
python3 ./convert.py /home/anarcho/Downloads/bitwarden_export_20230912103911.json -o passwords.kdbx
Traceback (most recent call last):
  File "/home/anarcho/.local/bin/bw2kp/bitwarden-to-keepass-1.0.0/bitwarden_to_keepass/./convert.py", line 17, in <module>
    import pykeepass
ModuleNotFoundError: No module named 'pykeepass'


I do not understand python - obviously!

**Comment by k3karthic** [comment]
You'll need to download all of the files from the repository and then install it with pip.

You can get a zip with all of the contents from [https://github.com/k3karthic/bitwarden-to-keepass/archive/refs/tags/v1.0.0.zip](https://github.com/k3karthic/bitwarden-to-keepass/archive/refs/tags/v1.0.0.zip).

Once you install it with pip you can use `bw2kp` to convert an exported vault.

```bash
> pip install --user .
> bw2kp -i /home/anarcho/Downloads/bitwarden_export_20230912103911.json -o pass.kdbx
```
