### ISSUE TITLE
NoneType has no length

### ISSUE THREAD

**Issue by pleonektikos** [k3karthic/bitwarden-to-keepass#8]
if len(item["login"].get("uris", [])) > 0:
TypeError: object of type 'NoneType' has no len()

How do I fix this?

**Comment by k3karthic** [comment]
It looks like the _uris_ field is set to null. I've pushed an update to the [devel](https://github.com/k3karthic/bitwarden-to-keepass/tree/devel) branch to fix this. Could you try it and let me know if it resolves the issue?

**Comment by k3karthic** [comment]
Released v0.1.9 with fix
